FROM {{ image_spec("base-tools") }}
MAINTAINER {{ maintainer }}

{{ copy_sources("seecloud/health", "/health") }}

RUN apt-get install --yes python-dev build-essential git-core

WORKDIR /health

RUN pip install -r requirements.txt
RUN python setup.py install

WORKDIR /health/health
